import Head from "next/head";
import React, { Suspense } from "react";
import BasicTable from "~/components/BasicTable";
import { getAccessToken, getSpotifyClient } from "~/utils/spotify";
import router, { useRouter } from "next/router";
import { Root as PlaylistTracksResponse } from "~/server/api/types/getPlaylistTracksResponse";
import { Song } from "~/components/BasicTable";
import Spinner from "~/components/Spinner";
const redirect = async () => {
  await router.push({ pathname: `/`, query: { auth_timed_out: true } });
};
const fetchPlaylistData = async (
  playlistId: string,
  token: string
): Promise<PlaylistTracksResponse> => {
  console.log(token);
  console.log(playlistId);
  const fetchedClient = getSpotifyClient(token);
  const res = await fetchedClient.get(
    `https://api.spotify.com/v1/playlists/${playlistId}/tracks`
  );
  return res.data as PlaylistTracksResponse;
};

const convertDataToSongsFormat = (data: PlaylistTracksResponse): Song[] =>
  data.items.map((item) => {
    const track = item.track;
    return {
    cover: track.album.images[0] ? new URL(track.album.images[0].url) : null,
    title: track.name,
    artist: track.artists[0]?.name ?? "unknown",
    album: track.album.name,
      dateAdded: new Date(item.added_at),
    length_ms: track.duration_ms,
    mp3: null,
    };
  });

const Home = () => {
  const router = useRouter();
  const playlistId = router.query["id"];
  const playlistName = router.query["playlist_name"];
  const playlistImgSrc = router.query["playlist_img_src"];
  const givenToken = router.query["token"];
  const [songs, setSongs] = React.useState(null as null | Song[]);
  console.log(playlistImgSrc);

  React.useEffect(() => {
    if (router.isReady) {
      (async () => {
        const data = await fetchPlaylistData(
          playlistId as unknown as string,
          givenToken as unknown as string
        );
        setSongs(convertDataToSongsFormat(data));
      })().catch((err) => {
        redirect().catch(() => console.log("uhh"));
        // console.log(err);
      });
    }
  }, [router.isReady]);

  return (
    <>
      <Head>
        <title>Create T3 App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="flex min-h-screen flex-col items-center justify-center">
        <div className="container flex flex-col items-center justify-center gap-12 px-4 py-16 ">
              <img src={playlistImgSrc as unknown as string}></img>
            </div>
          {songs ? <BasicTable songs={songs} /> : <Spinner />}
        </div>
      </main>
    </>
  );
};

export default Home;
