// Generated by ts-to-zod
import { z } from "zod";

export const externalUrlsSchema = z.object({
  spotify: z.string(),
});

export const imageSchema = z.object({
  height: z.number().optional(),
  url: z.string(),
  width: z.number().optional(),
});

export const externalUrls2Schema = z.object({
  spotify: z.string(),
});

export const ownerSchema = z.object({
  display_name: z.string(),
  external_urls: externalUrls2Schema,
  href: z.string(),
  id: z.string(),
  type: z.string(),
  uri: z.string(),
});

export const tracksSchema = z.object({
  href: z.string(),
  total: z.number(),
});

export const itemSchema = z.object({
  collaborative: z.boolean(),
  description: z.string(),
  external_urls: externalUrlsSchema,
  href: z.string(),
  id: z.string(),
  images: z.array(imageSchema),
  name: z.string(),
  owner: ownerSchema,
  primary_color: z.any().optional(),
  public: z.boolean(),
  snapshot_id: z.string(),
  tracks: tracksSchema,
  type: z.string(),
  uri: z.string(),
});

export default z.object({
  href: z.string(),
  items: z.array(itemSchema),
  limit: z.number(),
  next: z.string(),
  offset: z.number(),
  previous: z.any().optional(),
  total: z.number(),
});
