import { type NextPage } from "next";
import Head from "next/head";
import Link from "next/link";
import BasicTable from "~/components/BasicTable";
import Login from "~/components/Login";

import { api } from "~/utils/api";

const Home: NextPage = () => {
  const hello = api.example.hello.useQuery({ startsWith: "h" });
  const world = api.example.world.useQuery({ ownerId: hello.data?.id ?? 2 });
  // const spotify = api.spotify.getPlaylists.useQuery();

  return (
    <>
      <Head>
        <title>Create T3 App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="flex min-h-screen flex-col items-center justify-center">
        <div className="container flex flex-col items-center justify-center gap-12 px-4 py-16 ">
          <BasicTable />
          <Login />
          <p className="text-2xl text-black">
            {hello.data
              ? `${hello.data.name} ${hello.data.things[0]!.classification}`
              : "Loading tRPC query..."}
          </p>
          {/* <div>{spotify.data ? spotify.data.toString() : "uhh"}</div> */}
          
          {/* <Show when={token()} fallback={<Login />}>
        <Logout />
        <SelectPlaylist onChange={(id) => setPlaylistId(id)} />
        <Button onClick={logPlaylist}>Get Playlist Data</Button>
      </Show> */}
        </div>
      </main>
    </>
  );
};

export default Home;
