import Head from "next/head";

interface IAppProps {
  children?: React.ReactNode;
  title?: string;
  tailwindPadding?: string;
}

const Layout = ({ children, title, tailwindPadding }: IAppProps) => {
  const baseStyling =
    "container flex flex-col items-center justify-center gap-12";
  const paddedStyle = tailwindPadding
    ? `${baseStyling} ${tailwindPadding}`
    : `${baseStyling} px-4 py-16`;
  return (
    <>
      <Head>
        <title>{title ?? "Spotify Clone"}</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="flex min-h-screen flex-col items-center justify-center">
        <div className={paddedStyle}>{children}</div>
      </main>
    </>
  );
};

export default Layout;
