import Head from "next/head";

interface IAppProps {
  children?: React.ReactNode;
  title?: string;
}

const Layout = ({ children, title }: IAppProps) => {
  return (
    <>
      <Head>
        <title>{title ?? "Spotify Clone"}</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="flex min-h-screen flex-col items-center justify-center">
        <div className="container flex flex-col items-center justify-center gap-12 px-4 py-16">
          {children}
        </div>
      </main>
    </>
  );
};

export default Layout;
